SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.production_year>=1956.0 AND imdb_mc.company_type_id=2 AND imdb_mii.info_type_id=101 AND imdb_t.kind_id=1;||266208||107752
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.kind_id=3 AND imdb_mc.company_type_id=2 AND imdb_mii.info_type_id=99 AND imdb_t.production_year>=1974.0;||50805||15814
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_mc.company_type_id=2 AND imdb_mii.info_type_id=99 AND imdb_t.kind_id=1 AND imdb_t.production_year>=1999.0;||158431||108249
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.production_year=2002.0 AND imdb_t.kind_id=1 AND imdb_mii.info_type_id=99 AND imdb_mc.company_type_id=1;||11091||1581
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_mc.company_type_id=1 AND imdb_t.production_year>=2004.0 AND imdb_mii.info_type_id=100 AND imdb_t.kind_id=1;||142270||105018
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.kind_id=2 AND imdb_mii.info_type_id=100 AND imdb_mc.company_type_id=1;||57841||44323
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_mc.company_type_id=1 AND imdb_t.production_year>=1979.0 AND imdb_t.kind_id=1 AND imdb_mii.info_type_id=101;||296250||104902
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_mc.company_type_id=1 AND imdb_mii.info_type_id=99 AND imdb_t.production_year=1942.0;||3529||5962
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.kind_id=1 AND imdb_mc.company_type_id=1 AND imdb_t.production_year=2009.0 AND imdb_mii.info_type_id=101;||18602||1574
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mk.keyword_id=275 AND imdb_mc.company_type_id=1 AND imdb_t.production_year<=1986.0;||16315||4029
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=8430 AND imdb_mc.company_type_id=1;||5577||171
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.production_year>=1997.0 AND imdb_mk.keyword_id=1697 AND imdb_mc.company_type_id=2 AND imdb_t.kind_id=1;||2375||58
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mk.keyword_id=2964 AND imdb_mc.company_type_id=1 AND imdb_t.kind_id=1;||2124||171
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mc.company_type_id=2 AND imdb_mk.keyword_id=1716 AND imdb_t.kind_id=1 AND imdb_t.production_year>=2008.0;||287||58
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mk.keyword_id=1556 AND imdb_mc.company_type_id=1 AND imdb_t.production_year>=1999.0;||7856||215
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mc.company_type_id=2 AND imdb_t.production_year>=2002.0 AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=12589;||53||58
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mk.keyword_id=3736 AND imdb_t.production_year>=2001.0 AND imdb_t.kind_id=1 AND imdb_mc.company_type_id=1;||2001||57
SELECT COUNT(*) FROM movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.kind_id=1 AND imdb_t.production_year>=2008.0 AND imdb_mk.keyword_id=1941;||25615||879
SELECT COUNT(*) FROM movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.kind_id=1 AND imdb_t.production_year=1948.0 AND imdb_mk.keyword_id=121 AND imdb_mi.info_type_id=15;||199||33
SELECT COUNT(*) FROM movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mk.keyword_id=3627 AND imdb_mi.info_type_id=4 AND imdb_t.kind_id=1;||3347||231
SELECT COUNT(*) FROM movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mk.keyword_id=2241 AND imdb_mi.info_type_id=16 AND imdb_t.kind_id=1;||19130||540
SELECT COUNT(*) FROM movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.kind_id=1 AND imdb_t.production_year<=2007.0 AND imdb_mi.info_type_id=17 AND imdb_mk.keyword_id=723;||17020||22
SELECT COUNT(*) FROM movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.kind_id=1 AND imdb_t.production_year>=2002.0 AND imdb_mi.info_type_id=106 AND imdb_mk.keyword_id=123174;||23||7
SELECT COUNT(*) FROM movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mk.keyword_id=1608 AND imdb_t.kind_id=1 AND imdb_t.production_year>=1979.0;||56888||879
SELECT COUNT(*) FROM movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mi.info_type_id=15 AND imdb_mk.keyword_id=2860 AND imdb_t.kind_id=1;||23150||2762
SELECT COUNT(*) FROM movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mi.info_type_id=97 AND imdb_t.production_year=2000.0 AND imdb_t.kind_id=1;||28815||287
SELECT COUNT(*) FROM movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mk.keyword_id=41212 AND imdb_t.kind_id=1 AND imdb_mi.info_type_id=107;||38||25
SELECT COUNT(*) FROM movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.kind_id=4 AND imdb_t.production_year>=1994.0 AND imdb_mk.keyword_id=335 AND imdb_mi.info_type_id=2;||46338||3865
SELECT COUNT(*) FROM movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.production_year<=1999.0 AND imdb_mi.info_type_id=106 AND imdb_mk.keyword_id=2908;||585||28
SELECT COUNT(*) FROM movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.production_year<=1939.0 AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=2010 AND imdb_mi.info_type_id=5;||567||30
SELECT COUNT(*) FROM movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.production_year>=2002.0 AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=3483;||27816||879
SELECT COUNT(*) FROM movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.kind_id=1 AND imdb_mi.info_type_id=107 AND imdb_t.production_year=2006.0;||854261||2323
SELECT COUNT(*) FROM movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=12189 AND imdb_mi.info_type_id=17;||4791||65
SELECT COUNT(*) FROM movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=495 AND imdb_mi.info_type_id=8;||4137||6964
SELECT COUNT(*) FROM movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.production_year>=1940.0 AND imdb_mii.info_type_id=99 AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=6407;||229||23
SELECT COUNT(*) FROM movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.kind_id=1 AND imdb_t.production_year>=1982.0 AND imdb_mk.keyword_id=2488;||46701||9143
SELECT COUNT(*) FROM movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mk.keyword_id=10740 AND imdb_t.production_year<=2010.0 AND imdb_mii.info_type_id=101;||8||85
SELECT COUNT(*) FROM movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mii.info_type_id=101 AND imdb_mk.keyword_id=460 AND imdb_t.production_year>=1971.0;||4009||1860
SELECT COUNT(*) FROM movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mii.info_type_id=99 AND imdb_mk.keyword_id=6354 AND imdb_t.kind_id=3;||12||10
SELECT COUNT(*) FROM movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mk.keyword_id=10720 AND imdb_t.production_year<=1979.0 AND imdb_t.kind_id=1;||102||68
SELECT COUNT(*) FROM movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mk.keyword_id=6115 AND imdb_t.kind_id=2 AND imdb_t.production_year=1998.0;||6||1
SELECT COUNT(*) FROM movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mk.keyword_id=5169 AND imdb_t.production_year>=1993.0 AND imdb_mii.info_type_id=101 AND imdb_t.kind_id=1;||526||23
SELECT COUNT(*) FROM movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.production_year>=2010.0 AND imdb_mk.keyword_id=7771 AND imdb_t.kind_id=4;||39||199
SELECT COUNT(*) FROM movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.production_year<=2008.0 AND imdb_mii.info_type_id=100 AND imdb_t.kind_id=7;||264460||941507
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year=2011.0 AND imdb_t.kind_id=1 AND imdb_mi.info_type_id=5;||164618||3500
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.kind_id=1 AND imdb_t.production_year<=2010.0 AND imdb_mi.info_type_id=7 AND imdb_mc.company_type_id=2;||1290161||333449
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year<=1976.0 AND imdb_mi.info_type_id=18 AND imdb_mc.company_type_id=1;||459123||562196
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mi.info_type_id=16 AND imdb_t.production_year>=2001.0 AND imdb_t.kind_id=3;||185404||205277
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.kind_id=1 AND imdb_t.production_year<=2010.0 AND imdb_mc.company_type_id=2;||12032087||3477048
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year>=1976.0 AND imdb_mi.info_type_id=4 AND imdb_t.kind_id=3;||181760||88019
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year>=1997.0 AND imdb_t.kind_id=1 AND imdb_mc.company_type_id=1;||21619637||3385093
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year=2000.0 AND imdb_t.kind_id=1 AND imdb_mi.info_type_id=16;||239635||21077
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year>=1976.0 AND imdb_mi.info_type_id=7 AND imdb_t.kind_id=1 AND imdb_mc.company_type_id=1;||1471264||324630
SELECT COUNT(*) FROM cast_info imdb_ci, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_mk.keyword_id=956 AND imdb_t.kind_id=1 AND imdb_t.production_year=2009.0;||1086||12
SELECT COUNT(*) FROM cast_info imdb_ci, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_mk.keyword_id=28078 AND imdb_ci.role_id=4 AND imdb_t.production_year>=1997.0;||27||220
SELECT COUNT(*) FROM cast_info imdb_ci, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_mk.keyword_id=32059 AND imdb_ci.role_id=1 AND imdb_t.production_year=1944.0;||77||16
SELECT COUNT(*) FROM cast_info imdb_ci, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_mk.keyword_id=5210 AND imdb_ci.role_id=2 AND imdb_t.kind_id=1 AND imdb_t.production_year<=1996.0;||1438||165
SELECT COUNT(*) FROM cast_info imdb_ci, title imdb_t WHERE imdb_t.id=imdb_ci.movie_id AND imdb_t.kind_id=7 AND imdb_ci.role_id=8 AND imdb_t.production_year<=2004.0;||382026||362621
SELECT COUNT(*) FROM cast_info imdb_ci, title imdb_t WHERE imdb_t.id=imdb_ci.movie_id AND imdb_t.kind_id=1 AND imdb_ci.role_id=10 AND imdb_t.production_year>=1996.0;||724787||386770
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, title imdb_t WHERE imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mc.company_type_id=1 AND imdb_t.kind_id=1 AND imdb_ci.role_id=1 AND imdb_t.production_year=1934.0;||61314||21634
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, title imdb_t WHERE imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year>=2011.0 AND imdb_ci.role_id=4 AND imdb_t.kind_id=1 AND imdb_mc.company_type_id=1;||91025||302135
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, title imdb_t WHERE imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.kind_id=1 AND imdb_ci.role_id=10 AND imdb_mc.company_type_id=2 AND imdb_t.production_year>=1989.0;||2351543||512617
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, title imdb_t WHERE imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year=2001.0 AND imdb_mc.company_type_id=1 AND imdb_ci.role_id=2;||198102||48127
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, title imdb_t WHERE imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mc.company_type_id=1 AND imdb_ci.role_id=10 AND imdb_t.production_year<=1998.0;||3010052||1882300
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, title imdb_t WHERE imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mc.company_type_id=1 AND imdb_t.production_year=2005.0 AND imdb_ci.role_id=1;||580951||81598
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.kind_id=1 AND imdb_t.production_year<=1998.0 AND imdb_mii.info_type_id=100 AND imdb_mc.company_type_id=1;||18875160||3483958
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mc.company_type_id=1 AND imdb_t.kind_id=1 AND imdb_t.production_year>=2008.0 AND imdb_mii.info_type_id=101;||7316806||3480122
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year>=2009.0 AND imdb_mii.info_type_id=100 AND imdb_t.kind_id=1;||7513305||7062555
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mii.info_type_id=100 AND imdb_mi.info_type_id=7 AND imdb_t.kind_id=1;||2919068||2031897
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year>=1990.0 AND imdb_mc.company_type_id=1 AND imdb_t.kind_id=1 AND imdb_mii.info_type_id=101 AND imdb_mi.info_type_id=61;||37563||1419
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mii.info_type_id=101 AND imdb_mi.info_type_id=16 AND imdb_t.kind_id=1;||8123586||4333751
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.kind_id=1 AND imdb_mii.info_type_id=99 AND imdb_mc.company_type_id=1 AND imdb_mi.info_type_id=107;||2500526||101738
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mi.info_type_id=5 AND imdb_mc.company_type_id=1 AND imdb_mii.info_type_id=100;||3881432||1340320
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mc.company_type_id=2 AND imdb_t.production_year>=2002.0 AND imdb_mi.info_type_id=107 AND imdb_t.kind_id=1;||1119479||104231
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year<=1980.0 AND imdb_mc.company_type_id=2 AND imdb_mii.info_type_id=99;||2587182||13544628
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year=2001.0 AND imdb_t.kind_id=1 AND imdb_mc.company_type_id=1 AND imdb_mii.info_type_id=100;||1248132||52260
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mi.info_type_id=94 AND imdb_mc.company_type_id=2 AND imdb_t.kind_id=1;||537103||139691
SELECT COUNT(*) FROM movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_mii.info_type_id=99 AND imdb_mi.info_type_id=1 AND imdb_mk.keyword_id=58207 AND imdb_t.kind_id=1 AND imdb_t.production_year<=1965.0;||1||49
SELECT COUNT(*) FROM movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.kind_id=1 AND imdb_mii.info_type_id=100 AND imdb_t.production_year>=2012.0 AND imdb_mi.info_type_id=7;||261428||1575489
SELECT COUNT(*) FROM movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.production_year=2000.0 AND imdb_mi.info_type_id=98 AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=27560 AND imdb_mii.info_type_id=100;||1||1
SELECT COUNT(*) FROM movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.kind_id=1 AND imdb_mi.info_type_id=7 AND imdb_mii.info_type_id=99;||11122353||4743024
SELECT COUNT(*) FROM movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.kind_id=1 AND imdb_t.production_year>=2001.0 AND imdb_mi.info_type_id=8;||3968450||4484072
SELECT COUNT(*) FROM movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.production_year<=1984.0 AND imdb_mk.keyword_id=36167 AND imdb_mi.info_type_id=5;||132||348
SELECT COUNT(*) FROM movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_mii.info_type_id=99 AND imdb_t.production_year=2004.0 AND imdb_mi.info_type_id=7;||372329||89449
SELECT COUNT(*) FROM movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.production_year>=1933.0 AND imdb_t.kind_id=1 AND imdb_mii.info_type_id=101;||204393225||16410367
SELECT COUNT(*) FROM movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.kind_id=1 AND imdb_t.production_year<=2004.0 AND imdb_mi.info_type_id=16 AND imdb_mk.keyword_id=4255 AND imdb_mii.info_type_id=99;||5036||186
SELECT COUNT(*) FROM movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_mk.keyword_id=5603 AND imdb_mi.info_type_id=107 AND imdb_t.kind_id=1;||26352||79
SELECT COUNT(*) FROM movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_mk.keyword_id=8454 AND imdb_t.kind_id=1 AND imdb_mi.info_type_id=5 AND imdb_mii.info_type_id=99 AND imdb_t.production_year<=2011.0;||2345||31
SELECT COUNT(*) FROM movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_mii.info_type_id=100 AND imdb_t.kind_id=1 AND imdb_t.production_year>=1971.0;||173540809||16428454
SELECT COUNT(*) FROM movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.production_year>=1975.0 AND imdb_t.kind_id=1 AND imdb_mii.info_type_id=101 AND imdb_mk.keyword_id=2513;||5275||903
SELECT COUNT(*) FROM movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_mi.info_type_id=13 AND imdb_mii.info_type_id=99 AND imdb_t.kind_id=1;||13402896||583605
SELECT COUNT(*) FROM movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_mi.info_type_id=108 AND imdb_mii.info_type_id=99 AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=750 AND imdb_t.production_year=2005.0;||163||1
SELECT COUNT(*) FROM movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.production_year<=1990.0 AND imdb_mk.keyword_id=2387 AND imdb_mi.info_type_id=16;||5542||2097
SELECT COUNT(*) FROM movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_mi.info_type_id=77 AND imdb_t.kind_id=2 AND imdb_mk.keyword_id=851 AND imdb_t.production_year<=1990.0;||21||1
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mi.info_type_id=98 AND imdb_t.production_year=2003.0 AND imdb_t.kind_id=1;||2199970||28613
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year<=1968.0 AND imdb_mi.info_type_id=16 AND imdb_mk.keyword_id=16466;||16568||3556
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mc.company_type_id=1 AND imdb_mi.info_type_id=16 AND imdb_mk.keyword_id=1905;||207700||5263
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mc.company_type_id=2 AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=137;||2404075||601950
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mc.company_type_id=1 AND imdb_mi.info_type_id=46 AND imdb_t.production_year<=1996.0 AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=1714;||9980||1
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mc.company_type_id=1 AND imdb_mk.keyword_id=2082 AND imdb_t.production_year<=2011.0;||1560371||8568
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mi.info_type_id=15 AND imdb_mk.keyword_id=75361 AND imdb_mc.company_type_id=1;||29701||1059
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mi.info_type_id=17 AND imdb_t.production_year=1934.0 AND imdb_mc.company_type_id=1;||337418||57829
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mk.keyword_id=13666 AND imdb_mi.info_type_id=16 AND imdb_t.kind_id=1;||47510||2829
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mc.company_type_id=1 AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=11144 AND imdb_mi.info_type_id=15 AND imdb_t.production_year<=2005.0;||45298||94
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year<=1969.0 AND imdb_mk.keyword_id=26468 AND imdb_mc.company_type_id=1;||3361||8568
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year<=2002.0 AND imdb_mk.keyword_id=9287 AND imdb_t.kind_id=1 AND imdb_mc.company_type_id=1;||43830||2272
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mc.company_type_id=2 AND imdb_t.production_year=2005.0 AND imdb_mk.keyword_id=2241 AND imdb_mi.info_type_id=13 AND imdb_t.kind_id=1;||1648||1
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year>=2005.0 AND imdb_mi.info_type_id=15 AND imdb_mc.company_type_id=2;||34508064||6587341
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_ci.role_id=2 AND imdb_mk.keyword_id=1629 AND imdb_t.production_year=2007.0 AND imdb_mc.company_type_id=1;||4408||12
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mc.company_type_id=1 AND imdb_t.production_year=2009.0 AND imdb_t.kind_id=1;||172434659||281055
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.kind_id=1 AND imdb_ci.role_id=10 AND imdb_mk.keyword_id=41720;||5306||758
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mc.company_type_id=2 AND imdb_t.kind_id=1 AND imdb_t.production_year=1967.0;||1054186||288690
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.kind_id=1 AND imdb_mc.company_type_id=2 AND imdb_mk.keyword_id=41729 AND imdb_ci.role_id=10;||14989||384
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year>=1996.0 AND imdb_mc.company_type_id=1 AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=1074;||608073||1031
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.kind_id=1 AND imdb_t.production_year<=2009.0 AND imdb_mk.keyword_id=137 AND imdb_mc.company_type_id=1 AND imdb_ci.role_id=1;||2793775||30960
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.kind_id=1 AND imdb_mc.company_type_id=1 AND imdb_mk.keyword_id=28390 AND imdb_t.production_year=2005.0;||9870||15
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mc.company_type_id=1 AND imdb_mk.keyword_id=8976 AND imdb_t.production_year<=2011.0 AND imdb_ci.role_id=10;||20746||470
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mc.company_type_id=1 AND imdb_ci.role_id=10 AND imdb_mk.keyword_id=5117;||179557||1410
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.kind_id=1 AND imdb_mc.company_type_id=1 AND imdb_t.production_year<=1995.0 AND imdb_mk.keyword_id=4836;||110867||1031
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_ci.role_id=10 AND imdb_t.kind_id=4 AND imdb_mk.keyword_id=11389;||1043||136
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_ci.role_id=10 AND imdb_mi.info_type_id=7 AND imdb_t.kind_id=1;||12079848||5107229
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_ci.role_id=3 AND imdb_mi.info_type_id=106 AND imdb_t.kind_id=1 AND imdb_t.production_year>=2011.0;||270854||138830
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_mii.info_type_id=112 AND imdb_t.kind_id=1 AND imdb_t.production_year>=2005.0 AND imdb_ci.role_id=1;||1143354||5130
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_mii.info_type_id=99 AND imdb_ci.role_id=2 AND imdb_mi.info_type_id=4;||2370230||10045993
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.production_year>=1956.0 AND imdb_mii.info_type_id=101 AND imdb_mi.info_type_id=9 AND imdb_ci.role_id=1 AND imdb_t.kind_id=1;||1376795||150752
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_ci.role_id=3 AND imdb_mii.info_type_id=99 AND imdb_mi.info_type_id=6 AND imdb_t.kind_id=1;||308278||517789
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.kind_id=1 AND imdb_t.production_year<=2004.0 AND imdb_ci.role_id=10;||145646247||17751922
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_ci.role_id=10 AND imdb_t.kind_id=1 AND imdb_mii.info_type_id=101;||84704346||17716432
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.kind_id=1 AND imdb_t.production_year=1997.0 AND imdb_ci.role_id=10;||70255280||451606
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_mi.info_type_id=17 AND imdb_mc.company_type_id=1 AND imdb_t.production_year>=2012.0 AND imdb_ci.role_id=4 AND imdb_t.kind_id=1;||256073||222685
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_mi.info_type_id=17 AND imdb_t.kind_id=1 AND imdb_t.production_year=1981.0;||3879439||92589
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_ci.role_id=3 AND imdb_t.production_year<=2005.0 AND imdb_mi.info_type_id=5 AND imdb_mc.company_type_id=1;||13343126||1787338
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_mi.info_type_id=7 AND imdb_ci.role_id=2 AND imdb_t.kind_id=1;||36106032||14763607
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.production_year=1994.0 AND imdb_t.kind_id=1 AND imdb_mc.company_type_id=1 AND imdb_mi.info_type_id=17;||6420559||45674
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_mc.company_type_id=1 AND imdb_ci.role_id=7 AND imdb_mi.info_type_id=16 AND imdb_t.production_year<=2007.0;||4104534||642506
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_ci.role_id=3 AND imdb_t.kind_id=7 AND imdb_mc.company_type_id=2;||18825451||98268843
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_ci.role_id=10 AND imdb_mc.company_type_id=1 AND imdb_t.production_year<=2008.0 AND imdb_t.kind_id=1;||1375369013||14851635
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year<=1948.0 AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=14638 AND imdb_mc.company_type_id=1;||136277||7020
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year=2007.0 AND imdb_mc.company_type_id=1 AND imdb_mi.info_type_id=16;||115449479||1477588
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mii.info_type_id=101 AND imdb_mk.keyword_id=13037 AND imdb_mi.info_type_id=106;||112377||446
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mi.info_type_id=5 AND imdb_t.production_year<=2011.0 AND imdb_mk.keyword_id=2891 AND imdb_mii.info_type_id=100 AND imdb_mc.company_type_id=1;||286941||300
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mi.info_type_id=106 AND imdb_mii.info_type_id=101 AND imdb_t.kind_id=1;||291055812||2150264
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mii.info_type_id=100 AND imdb_mc.company_type_id=1 AND imdb_t.kind_id=6 AND imdb_t.production_year>=2004.0 AND imdb_mi.info_type_id=15;||1458679||30800
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year<=1987.0 AND imdb_mii.info_type_id=99 AND imdb_mc.company_type_id=1 AND imdb_t.kind_id=1;||982411246||42624405
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mk.keyword_id=2128 AND imdb_t.production_year=2010.0 AND imdb_mi.info_type_id=16 AND imdb_mc.company_type_id=1;||37995||81
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mii.info_type_id=99 AND imdb_mc.company_type_id=1 AND imdb_mi.info_type_id=108 AND imdb_t.kind_id=1;||37945282||144923
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year<=2002.0 AND imdb_mii.info_type_id=101 AND imdb_mk.keyword_id=3117;||146796||17855
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year<=1997.0 AND imdb_mii.info_type_id=100 AND imdb_mc.company_type_id=2;||211010863||164556544
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mk.keyword_id=10925 AND imdb_mi.info_type_id=107 AND imdb_t.production_year<=1989.0;||16688||521
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mii.info_type_id=101 AND imdb_mc.company_type_id=1 AND imdb_t.kind_id=1 AND imdb_mi.info_type_id=13;||323629521||1501981
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mc.company_type_id=1 AND imdb_mi.info_type_id=5 AND imdb_mk.keyword_id=7776 AND imdb_mii.info_type_id=99;||360636||903
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mi.info_type_id=7 AND imdb_t.kind_id=1 AND imdb_mii.info_type_id=99 AND imdb_t.production_year=2006.0;||9838909||124297
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=20868 AND imdb_t.production_year>=2003.0;||470860||14231
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.production_year<=2009.0 AND imdb_mi.info_type_id=16 AND imdb_mii.info_type_id=100;||635109488||66500262
SELECT COUNT(*) FROM movie_companies imdb_mc, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_mi.info_type_id=5 AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=82814 AND imdb_mc.company_type_id=1 AND imdb_mii.info_type_id=99;||1385||239
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_ci.role_id=10 AND imdb_t.production_year=2012.0 AND imdb_mc.company_type_id=1 AND imdb_mi.info_type_id=16 AND imdb_t.kind_id=1;||2715175754||556156
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mc.company_type_id=1 AND imdb_mi.info_type_id=18 AND imdb_t.production_year=2004.0;||876156815||3734203
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.kind_id=1 AND imdb_ci.role_id=10 AND imdb_mk.keyword_id=5762;||8509982||60609
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.kind_id=1 AND imdb_mc.company_type_id=1 AND imdb_t.production_year>=2006.0;||233657819759||1498904701
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.kind_id=2 AND imdb_mk.keyword_id=84 AND imdb_mc.company_type_id=1;||28048361||34819
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.kind_id=1 AND imdb_mi.info_type_id=107 AND imdb_ci.role_id=10 AND imdb_t.production_year<=2007.0;||18914961759||3560428
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.production_year=1995.0 AND imdb_ci.role_id=10 AND imdb_mk.keyword_id=2125;||3566861||1143
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_ci.role_id=3 AND imdb_t.kind_id=1 AND imdb_mc.company_type_id=1;||26816550812||509777468
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_ci.role_id=1 AND imdb_mc.company_type_id=1 AND imdb_t.production_year=1998.0;||3783190464||29605093
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mk.keyword_id=73059 AND imdb_mi.info_type_id=13 AND imdb_t.production_year>=1982.0 AND imdb_t.kind_id=1 AND imdb_ci.role_id=10 AND imdb_mc.company_type_id=1;||304420||118
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.production_year>=2001.0 AND imdb_ci.role_id=7 AND imdb_mk.keyword_id=5554 AND imdb_mi.info_type_id=15 AND imdb_t.kind_id=1 AND imdb_mc.company_type_id=1;||32943||23
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.kind_id=1 AND imdb_ci.role_id=10 AND imdb_mc.company_type_id=2 AND imdb_t.production_year>=2007.0 AND imdb_mk.keyword_id=97113;||67952||10237
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.kind_id=1 AND imdb_mi.info_type_id=5 AND imdb_mk.keyword_id=13440;||12497023||17059
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mc.company_type_id=1 AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=10648 AND imdb_mi.info_type_id=107;||27959701||2401
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mk.keyword_id=50930 AND imdb_mc.company_type_id=1 AND imdb_t.kind_id=1 AND imdb_t.production_year>=2006.0 AND imdb_mi.info_type_id=15 AND imdb_ci.role_id=10;||130650||411
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mc.company_type_id=2 AND imdb_t.production_year=1930.0 AND imdb_mk.keyword_id=1669 AND imdb_ci.role_id=1 AND imdb_mi.info_type_id=1;||220||91
SELECT COUNT(*) FROM cast_info imdb_ci, movie_companies imdb_mc, movie_info imdb_mi, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mc.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.production_year=1951.0 AND imdb_mk.keyword_id=16398 AND imdb_mi.info_type_id=16;||11222||1938
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_ci.role_id=2 AND imdb_mk.keyword_id=10737 AND imdb_mii.info_type_id=101;||477796||76428
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.production_year=2012.0 AND imdb_t.kind_id=1 AND imdb_mi.info_type_id=5 AND imdb_mk.keyword_id=3770;||2805||50
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.production_year>=1977.0 AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=2458 AND imdb_mii.info_type_id=101 AND imdb_mi.info_type_id=17;||212573||812
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_ci.role_id=2 AND imdb_t.production_year>=2010.0 AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=7478;||33447||20304
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mi.info_type_id=103 AND imdb_t.kind_id=7 AND imdb_mii.info_type_id=99;||4582278||18220648
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.kind_id=1 AND imdb_ci.role_id=1 AND imdb_mk.keyword_id=7637;||32012217||1876389
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mi.info_type_id=16 AND imdb_mk.keyword_id=52119 AND imdb_mii.info_type_id=99 AND imdb_t.production_year<=2006.0;||9742||25452
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mi.info_type_id=13 AND imdb_t.production_year>=2006.0 AND imdb_ci.role_id=10;||1279044537||9632287
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.kind_id=1 AND imdb_ci.role_id=10 AND imdb_mk.keyword_id=7350 AND imdb_mii.info_type_id=100;||1382057||11902
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mii.info_type_id=100 AND imdb_mk.keyword_id=40207 AND imdb_t.kind_id=6;||9768||1734
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.production_year>=2004.0 AND imdb_mk.keyword_id=1929 AND imdb_mii.info_type_id=99;||441052||124300
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_ci.role_id=1 AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=129649 AND imdb_mii.info_type_id=100 AND imdb_t.production_year<=1995.0 AND imdb_mi.info_type_id=17;||2240||284
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.kind_id=1 AND imdb_t.production_year=2009.0 AND imdb_mii.info_type_id=112;||133788040||2687
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_t.kind_id=1 AND imdb_t.production_year=1951.0 AND imdb_mi.info_type_id=3 AND imdb_mii.info_type_id=101 AND imdb_ci.role_id=1;||996880||300141
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info imdb_mi, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mi.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mk.movie_id AND imdb_mi.info_type_id=103 AND imdb_ci.role_id=10 AND imdb_mk.keyword_id=359 AND imdb_t.kind_id=1;||191313||19094
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_mii.info_type_id=101 AND imdb_ci.role_id=2 AND imdb_mk.keyword_id=15470 AND imdb_t.production_year<=2006.0 AND imdb_t.kind_id=1;||1654||76
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.production_year=2007.0 AND imdb_t.kind_id=1 AND imdb_mii.info_type_id=101 AND imdb_mk.keyword_id=24261;||1191||6
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_mk.keyword_id=2292 AND imdb_mii.info_type_id=101 AND imdb_ci.role_id=2 AND imdb_t.kind_id=1;||15276||227
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.kind_id=1 AND imdb_t.production_year<=2005.0 AND imdb_mk.keyword_id=733 AND imdb_mii.info_type_id=101;||44930||368
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=4607 AND imdb_mii.info_type_id=100 AND imdb_t.production_year=2003.0;||4422||6
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.kind_id=1 AND imdb_mk.keyword_id=980 AND imdb_ci.role_id=1 AND imdb_t.production_year=1973.0;||735||6
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_t.kind_id=1 AND imdb_mii.info_type_id=100 AND imdb_mk.keyword_id=1901;||36296||1105
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_mk.keyword_id=5223 AND imdb_t.kind_id=1 AND imdb_ci.role_id=1 AND imdb_mii.info_type_id=100;||3279||386
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_ci.role_id=2 AND imdb_t.kind_id=1 AND imdb_t.production_year=1999.0 AND imdb_mii.info_type_id=101;||657412||20642
SELECT COUNT(*) FROM cast_info imdb_ci, movie_info_idx imdb_mii, movie_keyword imdb_mk, title imdb_t WHERE imdb_t.id=imdb_mk.movie_id AND imdb_t.id=imdb_ci.movie_id AND imdb_t.id=imdb_mii.movie_id AND imdb_ci.role_id=1 AND imdb_mk.keyword_id=1050 AND imdb_t.kind_id=1;||95550||1158